#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfb30;
constexpr uint24_t FX_DATA_BYTES = 311287;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t Cards_Bottom = 0x018810;
  constexpr uint24_t Cards_Bottom_Grey = 0x01CDAE;
  constexpr uint24_t Cards_Left = 0x02134C;
  constexpr uint24_t Cards_Right = 0x026C40;
  constexpr uint24_t Hand_Left = 0x02C534;
  constexpr uint24_t Hand_Right = 0x02CBA8;
  constexpr uint24_t Hand_Top = 0x02D21C;
  constexpr uint24_t PPOT = 0x02DD34;
  constexpr uint24_t Sound_Volume_Grey = 0x030D36;
  constexpr uint24_t Sound_Volume_White = 0x031578;
  constexpr uint24_t Sound_Checkbox = 0x031DBA;
  constexpr uint24_t Title = 0x031DC8;
  constexpr uint24_t HUD = 0x03614A;
  constexpr uint24_t Score_Numbers_Bottom = 0x036E3C;
  constexpr uint24_t Score_Numbers_Left = 0x036F3A;
  constexpr uint24_t Score_Numbers_Right = 0x037038;
  constexpr uint24_t Bid = 0x037136;
  constexpr uint24_t Numbers_3x5 = 0x037B04;
  constexpr uint24_t HighScores = 0x03A8BA;
  constexpr uint24_t HUD_Trick_Score = 0x03B2AC;
  constexpr uint24_t HUD_Game_Score = 0x03B380;
  constexpr uint24_t Hand_Full = 0x03D452;
  constexpr uint24_t Hand_Full_Grey = 0x03D4ED;
  constexpr uint24_t Rotate = 0x03D588;
  constexpr uint24_t Flip = 0x043ACA;
  constexpr uint24_t Bid_Panel = 0x044CCC;
  constexpr uint24_t Bid_Suits = 0x0462BE;
  constexpr uint24_t Bid_Numbers = 0x0463CE;
  constexpr uint24_t Bid_Bottom = 0x0464A2;
  constexpr uint24_t Bid_Left = 0x0474D0;
  constexpr uint24_t Bid_Right = 0x0485B2;
  constexpr uint24_t Bid_Result = 0x049694;
  constexpr uint24_t Bid_Result_Narrow = 0x04A33E;
  constexpr uint24_t Title500 = 0x04A9E5;
  constexpr uint24_t Dealer = 0x04B5E7;
  constexpr uint24_t EveryonePassed = 0x04B5F8;
  constexpr uint24_t KittyInstructions = 0x04B6D8;
  constexpr uint24_t ChooseSuit = 0x04B911;
}

