#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfa7e;
constexpr uint24_t FX_DATA_BYTES = 356817;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t Cards_Bottom = 0x018810;
  constexpr uint24_t Cards_Bottom_Grey = 0x01CDAE;
  constexpr uint24_t Cards_Left = 0x02134C;
  constexpr uint24_t Cards_Right = 0x026C40;
  constexpr uint24_t Hand_Left = 0x02C534;
  constexpr uint24_t Hand_Right = 0x02CBA8;
  constexpr uint24_t Hand_Top = 0x02D21C;
  constexpr uint24_t PPOT = 0x02DD34;
  constexpr uint24_t Sound_Volume_Grey = 0x030D36;
  constexpr uint24_t Sound_Volume_White = 0x031578;
  constexpr uint24_t Sound_Checkbox = 0x031DBA;
  constexpr uint24_t Title = 0x031DC8;
  constexpr uint24_t HUD_Top = 0x03614A;
  constexpr uint24_t HUD_Bottom = 0x0366B0;
  constexpr uint24_t Score_Numbers_Bottom = 0x036C16;
  constexpr uint24_t Score_Numbers_Left = 0x036D14;
  constexpr uint24_t Score_Numbers_Right = 0x036E12;
  constexpr uint24_t Bid = 0x036F10;
  constexpr uint24_t Numbers_3x5 = 0x0378DE;
  constexpr uint24_t HighScores = 0x03A694;
  constexpr uint24_t HUD_Trick_Score = 0x03B086;
  constexpr uint24_t HUD_Game_Score = 0x03B15A;
  constexpr uint24_t Hand_Full = 0x03D22C;
  constexpr uint24_t Hand_Full_Grey = 0x03D2C7;
  constexpr uint24_t Rotate = 0x03D362;
  constexpr uint24_t Flip = 0x0438A4;
  constexpr uint24_t Bid_Panel = 0x044AA6;
  constexpr uint24_t Bid_Suits = 0x046098;
  constexpr uint24_t Bid_Numbers = 0x0461A8;
  constexpr uint24_t Bid_Bottom = 0x04627C;
  constexpr uint24_t Bid_Left = 0x0472AA;
  constexpr uint24_t Bid_Right = 0x04838C;
  constexpr uint24_t Bid_Result = 0x04946E;
  constexpr uint24_t Bid_Result_Narrow = 0x04A118;
  constexpr uint24_t Title500 = 0x04A7BF;
  constexpr uint24_t Dealer = 0x0567C1;
  constexpr uint24_t EveryonePassed = 0x0567D2;
  constexpr uint24_t KittyInstructions = 0x0568B2;
  constexpr uint24_t ChooseSuit = 0x056AEB;
}

