#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfc22;
constexpr uint24_t FX_DATA_BYTES = 249104;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Music
{
  constexpr uint24_t Song_MainTheme = 0x000000;
  constexpr uint24_t SFX_Death = 0x018580;
  constexpr uint24_t SFX_Victory = 0x018624;
  constexpr uint24_t SFX_XPGain = 0x0186D8;
  constexpr uint24_t SFX_Three_Inc = 0x0186EC;
  constexpr uint24_t SFX_Three_Dec = 0x018708;
  constexpr uint24_t SFX_PlayerBlip = 0x018724;
  constexpr uint24_t SFX_EnemyBlip = 0x018734;
  constexpr uint24_t SFX_Explosion = 0x018744;
  constexpr uint24_t SFX_DoubleBeep = 0x018788;
  constexpr uint24_t SFX_DoubleBeepDown = 0x018798;
  constexpr uint24_t SFX_Bet1 = 0x0187A8;
  constexpr uint24_t SFX_Bet2 = 0x0187B0;
  constexpr uint24_t SFX_Bet3 = 0x0187B8;
  constexpr uint24_t SFX_Bet4 = 0x0187C0;
  constexpr uint24_t SFX_Bet5 = 0x0187C8;
  constexpr uint24_t SFX_Bet6 = 0x0187D0;
  constexpr uint24_t SFX_Click = 0x0187D8;
  constexpr uint24_t SFX_SmallBlind = 0x0187E0;
  constexpr uint24_t SFX_BigBlind = 0x0187E8;
}

namespace Constants
{
  constexpr uint24_t Starting_Bids = 0x0187F8;
  constexpr uint24_t Score_Panel_XTextPos = 0x0187FE;
  constexpr uint24_t Score_Panel_XPanelPos = 0x018804;
  constexpr uint24_t Score_Panel_Idx = 0x01880A;
}

namespace Images
{
  constexpr uint24_t Cards_Bottom = 0x018810;
  constexpr uint24_t Cards_Left = 0x01BFC2;
  constexpr uint24_t Cards_Right = 0x020074;
  constexpr uint24_t Hand_Left = 0x02479E;
  constexpr uint24_t Hand_Right = 0x024E12;
  constexpr uint24_t Hand_Top = 0x025486;
  constexpr uint24_t PPOT = 0x025F9E;
  constexpr uint24_t Sound_Volume_Grey = 0x028FA0;
  constexpr uint24_t Sound_Volume_White = 0x0297E2;
  constexpr uint24_t Sound_Checkbox = 0x02A024;
  constexpr uint24_t Title = 0x02A032;
  constexpr uint24_t HUD = 0x02E3B4;
  constexpr uint24_t Score_Numbers_Bottom = 0x02E5DE;
  constexpr uint24_t Score_Numbers_Left = 0x02E6DC;
  constexpr uint24_t Score_Numbers_Right = 0x02E7DA;
  constexpr uint24_t Bid = 0x02E8D8;
  constexpr uint24_t Numbers = 0x02F2A6;
  constexpr uint24_t Numbers_3x5 = 0x02F668;
  constexpr uint24_t Arrows = 0x03241E;
  constexpr uint24_t HighScores = 0x03246E;
  constexpr uint24_t Dealer = 0x032E60;
  constexpr uint24_t Hand_Full = 0x032E71;
  constexpr uint24_t Rotate = 0x032F0C;
  constexpr uint24_t Flip = 0x03944E;
  constexpr uint24_t Bid_Panel = 0x03A650;
  constexpr uint24_t Bid_Suits = 0x03BF2A;
  constexpr uint24_t Bid_Numbers = 0x03C03A;
  constexpr uint24_t Title500 = 0x03C10E;
}

